[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  set conceallevel=0
  let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("nvim") && has("python3")'
on_cmd = ['Denite', 'DeniteCursorWord']
hook_add = '''
nmap <silent> <C-p> :<C-u>Denite -default-action=tabopen file_rec<CR>
nmap <silent> <C-g> :<C-u>Denite -default-action=tabopen grep<CR>
'''
hook_source = '''

call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-p>", '<denite:move_to_previous_line>')
call denite#custom#map('normal', "<C-n>", '<denite:move_to_next_line>')
call denite#custom#map('normal', "<C-p>", '<denite:move_to_previous_line>')

" tabopen や vsplit のキーバインドを割り当て
call denite#custom#map('insert', "<C-t>", '<denite:do_action:tabopen>')
call denite#custom#map('insert', "<C-v>", '<denite:do_action:vsplit>')
call denite#custom#map('insert', "<C-s>", '<denite:do_action:split>')
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
  let g:vim_markdown_conceal = 0
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

# HTML5 ominicomplete & syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'htmldjango']

# CSS3 syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# Coq syntax
[[plugins]]
repo = 'jvoorhis/coq.vim'
on_ft = 'coq'

# Scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = "nvie/vim-flake8"
on_ft = 'python'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_source = '''
let g:jedi#goto_command = "<C-]>"
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#show_call_signatures=0

" jedi での補完は OFF
let g:jedi#completions_enabled=0
'''

[[plugins]]
repo = 'hotchpotch/perldoc-vim'
on_ft = 'perl'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_source = 'source ~/.vim/config/plugins/neosnippet.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = 'typescript'
hook_add = '''
let g:tsuquyomi_definition_split = 3
'''
# 0: |:edit|
# 1: |:split|
# 2: |:vplit|
# 3: |:tabedit|

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source = 'source ~/.vim/config/plugins/tex.vim'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NerdTreeToggle'
hook_add = '''
  let g:NERDTreeShowHidden = 1
'''
