[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'md'

[[plugins]]
repo = 'kannokanno/previm'
on_cmd = 'PrevimOpen'

# HTML5 ominicomplete & syntax
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htmldjango']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'htmldjango']

# CSS3 syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

# Coq syntax
[[plugins]]
repo = 'jvoorhis/coq.vim'
on_ft = 'coq'

# Scala
[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

# TOML
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = "nvie/vim-flake8"
on_ft = 'python'

[[plugins]]
repo = 'hotchpotch/perldoc-vim'
on_ft = 'perl'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = "has('lua')"
on_event = 'InsertEnter'
hook_source = '''
  let g:neocomplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
on_event = 'InsertEnter'
on_ft = 'snippet'
hook_source = 'source ~/.vim/config/plugins/neosnippet.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
